### ISSUE TITLE
代码中有个导包的代码需要修改一下

### ISSUE THREAD

**Issue by acezsq** [ACking-you/byte_douyin_project#11]
byte_douyin_project/deprecated/middleware/normal.go文件中应该是import github.com/ACking-you/byte_douyin_project/models而不是import github.com/ACking-you/byte_douyin_project/models/deprecated

**Comment by ACking-you** [comment]
有空的话你可以提个pr改一下，我会非常感激。我应该是不会再改这个仓库了

**Comment by zxs-000202** [comment]
已提交pr
