### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 13194239636** [ACking-you/byte_douyin_project#6]
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/gin-gonic/gin v1.7.7
go: finding github.com/golang/protobuf v1.5.2
go: finding github.com/nxadm/tail v1.4.8
go: finding gorm.io/driver/mysql v1.3.3
go: finding gorm.io/gorm v1.23.5
go: finding github.com/fsnotify/fsnotify v1.4.9
go: golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 172.217.163.49:443: i/o timeout)
go: finding github.com/onsi/gomega v1.18.1
go: golang.org/x/sys@v0.0.0-20211216021012-1d35b9e2eb4e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 172.217.163.49:443: i/o timeout)
go: finding github.com/onsi/ginkgo v1.16.5
go: golang.org/x/text@v0.3.6: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 172.217.163.49:443: i/o timeout)
go: github.com/golang/protobuf@v1.5.2: unknown revision v1.5.2
go: gorm.io/driver/mysql@v1.3.3: unknown revision v1.3.3
go: gorm.io/gorm@v1.23.5: unknown revision v1.23.5
go: github.com/nxadm/tail@v1.4.8: unknown revision v1.4.8
go: github.com/onsi/gomega@v1.18.1: unknown revision v1.18.1
go: github.com/dgrijalva/jwt-go@v3.2.0+incompatible: unknown revision v3.2.0
go: github.com/gin-gonic/gin@v1.7.7: unknown revision v1.7.7
go: github.com/onsi/ginkgo@v1.16.5: unknown revision v1.16.5
go: error loading module requirements

**Comment by 13194239636** [comment]
请问我执行go run main.go后报错是什么原因？网络问题导致依赖下载失败吗

**Comment by ACking-you** [comment]
我看你的报错信息很可能是因为goproxy的代理出现的问题，就是依赖都安装成功了，还需要有mysql和redis环境，还有本地需要有gcc环境(用于执行命令命令)，最后就是这个项目也很久没有维护了，我有时间再看看什么原因，两天内应该有时间腾出

**Comment by 13194239636** [comment]
本地环境我都安装好了，包括mysql8.0，redis7.0.7 gcc10.2，可能是其它原因，想借这个项目学习下go，麻烦你近期帮我看看启动失败具体原因

**Comment by ACking-you** [comment]
你把本地的go env变量输出打印给我看下

**Comment by 13194239636** [comment]
mac@MacdeMacBook-Pro ~ % go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mac/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gh/54w67t6n7_b8pv7t76xw5_qm0000gn/T/go-build090288493=/tmp/go-build -gno-record-gcc-switches -fno-common"
mac@MacdeMacBook-Pro ~ %

**Comment by ACking-you** [comment]
go env -w GOPROXY=https://goproxy.cn,direct

输入上述命令后，再试试go get看看，如果仍然出错再把结果发给我看看，我明天抽出时间看看
