### ISSUE TITLE
启动成功后访问报错

### ISSUE THREAD

**Issue by 13194239636** [ACking-you/byte_douyin_project#7]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24969221/210065170-98bc8fc4-182d-49c1-a531-e0f062f67cae.png">
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/24969221/210065228-8dbb2244-1c31-41b9-b86d-2c3193a08069.png">

**Comment by ACking-you** [comment]
请带上你的数据表，以及对应的哪个api请求发生错误，我建议使用postman或者apifox对接口进行调试

**Comment by 13194239636** [comment]
启动后前端界面没显示，你的项目是只有后端吗？

**Comment by ACking-you** [comment]
> 启动后前端界面没显示，你的项目是只有后端吗？

前端是抖音的APP，APP链接在这里：https://vfchdrh6q6.feishu.cn/docx/doxcnwTuJ3CbOFDhQan4EQBrKWg ​
