### ISSUE TITLE
请问建表的时候把login信息和user_info的信息建到一张表里可以么

### ISSUE THREAD

**Issue by zcwhy** [ACking-you/byte_douyin_project#8]

**Comment by ACking-you** [comment]
看你自己，表设计无所谓，改下代码就好了

**Comment by zcwhy** [comment]
> 看你自己，表设计无所谓，改下代码就好了

我看了好多都是分开来设计的， 如果是合起来这样的设计的话是不是有什么缺点啊

**Comment by ACking-you** [comment]
> > 看你自己，表设计无所谓，改下代码就好了
> 
> 我看了好多都是分开来设计的， 如果是合起来这样的设计的话是不是有什么缺点啊

自己搜下设计数据库的范式
